### ISSUE TITLE
Timestamps in the output should have consistent format 

### ISSUE THREAD

**Issue by Michalski-Piotr** [ailog-analytics/wls-analytics#10]
Hello,

There are some lines in the output, where milliseconds  are skipped and timestamp is ```2023-10-09 08:10:51```:

```console

[oracle@k8s-registry logs]$ grep XML-23006 iter_20231031-131157.txt | grep "2023-10-09 08:10:51"
2023-10-09 08:10:51         soa_server4  1334785832  SyncCustomerPartyListBRMCommsProvABCSImpl                     XML-23006                    SyncCustomerPartyListEBM_To_PCM_OP_CUST_UPDATE_CUSTOMER_inputFlist.xsl|XML-23006                       zicu54
```

For majority of lines timestamp is with milliseconds part, example ```2023-10-09 00:51:47.915000```:

```console

[oracle@k8s-registry logs]$ grep XML-23006 iter_20231031-131157.txt | head -10
2023-10-09 00:51:47.915000  soa_server3  1334202434  SyncCustomerPartyListBRMCommsProvABCSImpl                     XML-23006                    SyncCustomerPartyListEBM_To_PCM_OP_CUST_UPDATE_CUSTOMER_inputFlist.xsl|XML-23006                       tula49
2023-10-09 01:07:16.554000  soa_server3  1334196658  SyncCustomerPartyListBRMCommsProvABCSImpl                     XML-23006                    SyncCustomerPartyListEBM_To_PCM_OP_CUST_UPDATE_CUSTOMER_inputFlist.xsl|XML-23006                       zefo68
2023-10-09 01:14:15.854000  soa_server5  1334178407  SyncCustomerPartyListBRMCommsProvABCSImpl                     XML-23006                    SyncCustomerPartyListEBM_To_PCM_OP_CUST_UPDATE_CUSTOMER_inputFlist.xsl|XML-23006                       nezo87
2023-10-09 02:18:46.675000  soa_server3  1334318007  SyncCustomerPartyListBRMCommsProvABCSImpl                     XML-23006                    SyncCustomerPartyListEBM_To_PCM_OP_CUST_UPDATE_CUSTOMER_inputFlist.xsl|XML-23006                       kebo58
2023-10-09 02:34:02.672000  soa_server5  1334318007  SyncCustomerPartyListBRMCommsProvABCSImpl                     XML-23006                    SESSIONS_IN_USE_110                                                                                    koce23
2023-10-09 03:38:32.304000  soa_server4  1334488493  SyncCustomerPartyListBRMCommsProvABCSImpl                     XML-23006                    SyncCustomerPartyListEBM_To_PCM_OP_CUST_UPDATE_CUSTOMER_inputFlist.xsl|XML-23006                       kiko85
2023-10-09 07:19:46.240000  soa_server4  1334736488  SyncCustomerPartyListBRMCommsProvABCSImpl                     XML-23006                    SyncCustomerPartyListEBM_To_PCM_OP_CUST_UPDATE_CUSTOMER_inputFlist.xsl|XML-23006                       zeku12
2023-10-09 07:21:18.594000  soa_server2  1334738920  SyncCustomerPartyListBRMCommsProvABCSImpl                     XML-23006                    SyncCustomerPartyListEBM_To_PCM_OP_CUST_UPDATE_CUSTOMER_inputFlist.xsl|XML-23006                       nuzo98
2023-10-09 07:26:18.864000  soa_server3  1334738920  SyncCustomerPartyListBRMCommsProvABCSImpl                     XML-23006                    SyncCustomerPartyListEBM_To_PCM_OP_CUST_UPDATE_CUSTOMER_inputFlist.xsl|XML-23006                       wuxa61
2023-10-09 07:29:46.483000  soa_server3  1334736488  SyncCustomerPartyListBRMCommsProvABCSImpl                     XML-23006                    SyncCustomerPartyListEBM_To_PCM_OP_CUST_UPDATE_CUSTOMER_inputFlist.xsl|XML-23006                       zemu44

```

This mismatch is causing issues, if wlsanalitics tool output is processed by other script. 
The timestamp in my opinion should be always in format ```format='%Y-%m-%d %H:%M:%S.%f'``` even when milliseconds are only 0.

Regards,
Piotr Michalski

**Comment by Michalski-Piotr** [comment]
Reproduce set:


```console
wlsanalytics log soa error -c config/config.yaml -f '2023-10-09 00:00:00' -t '2023-10-10 00:00:00'  o2c --index | tee -a logs/iter_$(date "+%Y%m%d-%H%M%S").txt

```

Logs are uploaded here:

```console


[oracle@k8s-registry o2c]$ hostname
k8s-registry
[oracle@k8s-registry o2c]$ pwd
/home/oracle/wlsanalytics/data/o2c
[oracle@k8s-registry o2c]$ ls -l o2c_20231011_logs.tar.gz
-rw-r--r-- 1 oracle oinstall 1568587402 Oct 11 13:18 o2c_20231011_logs.tar.gz
```

Regards,
Piotr

**Comment by tomvit** [comment]
This is likely related to https://github.com/ailog-analytics/wls-analytics/issues/3. 

The problem is that some WLS loggers use different time format. Since wlsanalytics tool parses the time into the datetime, it should be possible to fix this internally in the tool.

**Comment by Michalski-Piotr** [comment]
Hi,
I think due to the fact issue was observed for the same error type ```XML-23006``` and the same composite SyncCustomerPartyListBRMCommsProvABCSImpl, it is rather due to the fact particular error happened exactly 0 ms after full second. This is confirmed using index entry below, timestamp in the log is ```Oct 9, 2023 8:10:51,000 AM UTC```:

```console


[oracle@k8s-registry wlsanalytics]$ wlsanalytics log soa error -c config/config.yaml -f '2023-10-09 08:10:50' -t '2023-10-09 08:10:52' o2c --index | tee -a ~/wlsanalytics/logs/issue_10_repro.txt
-- Time range: 2023-10-09 08:10:50 - 2023-10-09 08:10:52
-- The index will be created.
-- Searching files in the set 'o2c'
-- Reading entries from 5 files:   2%|▌                         | 2.22M/103M [00:00<00:37, 2.79MB/s]
-- Completed in 3.69s
TIME                        SERVER       FLOW_ID     COMPOSITE                                  ERROR                  DETAIL                                                                            INDEX

2023-10-09 08:10:51         soa_server4  1334785832  SyncCustomerPartyListBRMCommsProvABCSImpl  XML-23006              SyncCustomerPartyListEBM_To_PCM_OP_CUST_UPDATE_CUSTOMER_inputFlist.xsl|XML-23006  fuke73
-- Errors: 2
 

[oracle@k8s-registry wlsanalytics]$ wlsanalytics log index fuke73 --stdout
index_id    : fuke73
log_file    : /u01/oracle/wlsanalytics/data/o2c/soa_server4/logs/soa_server4.out12220
index_file  : /u01/oracle/wlsanalytics/data/index/wlsa-soaerrors-972.index

<Oct 9, 2023 8:10:51,000 AM UTC> <Error> <oracle.soa.bpel.engine> <BEA-000000> <
 ** Cikey: 14627499341
 ** FlowId: 1334785832
 ** Current Activity Key: 14627499341-BpAss115-BpSeq64.49-1
 ** Current Activity Label: Xform_SyncCustomerPartyListEBM_To_PCM_OP_CUST_UPDATE_CUSTOMER_inputFlist
 ** ComponentDN: default/SyncCustomerPartyListBRMCommsProvABCSImpl!1.5.0.1*soa_5aa00aa4-4732-46f2-b1fe-135ee0f4c4d5/SyncCustomerPartyListBRMCommsProvABCSImpl
 ** Properties for component SyncCustomerPartyListBRMCommsProvABCSImpl:
   ** bpel.config.oneWayDeliveryPolicy: sync
   ** bpel.config.transaction: required
   ** bpel.config.inMemoryOptimization: true
   ** bpel.config.completionPersistPolicy: faulted
   ** bpel.preference.anonymousCity: not known
   ** bpel.preference.anonymousPostalCode: XX9 9XX
   ** bpel.preference.anonymousStreet: not known
   ** bpel.preference.anonymousCountry: United Kingdom
   ** bpel.preference.InvokeErrorResponseEBS: false
 ** Transaction info: Xid=BEA1-0ADD8148C56108136700(1270198882),Status=Active,numRepliesOwedMe=0,numRepliesOwedOthers=0,seconds since begin=0,seconds left=319,useSecure=false,XAServerResourceInfo[oracle.tip.adapter.jms.JmsXAResource]=(ServerResourceInfo[oracle.tip.adapter.jms.JmsXAResource]=(state=suspended,assigned=none),xar=oracle.tip.adapter.jms.JmsXAResource@3c03eda8,re-Registered = false),XAServerResourceInfo[WLStore_o2c-domain_AIADataStore_auto_1]=(ServerResourceInfo[WLStore_o2c-domain_AIADataStore_auto_1]=(state=new,assigned=none),xar=null,re-Registered = false),XAServerResourceInfo[XrefDataSource_o2c-domain]=(ServerResourceInfo[XrefDataSource_o2c-domain]=(state=started,assigned=none),xar=XrefDataSource,re-Registered = false),SCInfo[o2c-domain+soa_server4]=(state=active),SCInfo[o2c-domain+soa_server1]=(state=active),properties=({weblogic.transaction.partitionName=DOMAIN, weblogic.jdbc.affinity.prfmxexa.PRFMX=oracle.ucp.jdbc.oracle.OracleConnectionAffinityContext: versionNumber=1.0, isForInstanceAffinity=true, connectionPoolID=null, instanceName=prfmx1, dbUniqName=prfmxexa, serviceName=PRFMX}),local properties=({weblogic.jdbc.jta.XrefDataSource=[groups=[(instance,prfmx1)],switchingContext=null,autoCommit=true,enabled=true,isXA=true,isJTS=false,vendorID=0,connUsed=true,doInit=false,'null',destroyed=false,poolname=XrefDataSource,appname=null,moduleName=null,connectTime=30,dirtyIsolationLevel=false,initialIsolationLevel=2,infected=false,lastSuccessfulConnectionUse=1696839050998,secondsToTrustAnIdlePoolConnection=0,currentUser=java.lang.Exception
	at weblogic.jdbc.common.internal.ConnectionEnv.setup(ConnectionEnv.java:464)
	at weblogic.common.resourcepool.ResourcePoolImpl.reserveResource(ResourcePoolImpl.java:404)
	at weblogic.jdbc.common.internal.HAConnectionPool.reserve(HAConnectionPool.java:350)
	at weblogic.jdbc.common.internal.HAConnectionPool.reserve(HAConnectionPool.java:242)
	at weblogic.jdbc.common.internal.ConnectionPoolManager.reserve(ConnectionPoolManager.java:148)
	at weblogic.jdbc.common.internal.ConnectionPoolManager.reserve(ConnectionPoolManager.java:94)
	at weblogic.jdbc.jta.DataSource.getXAConnectionFromPool(DataSource.java:1938)
	at weblogic.jdbc.jta.DataSource.refreshXAConnAndEnlist(DataSource.java:1645)
	at weblogic.jdbc.jta.DataSource.getConnectionInternal(DataSource.java:523)
	at weblogic.jdbc.jta.DataSource.getConnection(DataSource.java:500)
	at weblogic.jdbc.common.internal.WLDataSourceImpl.getConnectionInternal(WLDataSourceImpl.java:631)
	at weblogic.jdbc.common.internal.WLDataSourceImpl.getConnection(WLDataSourceImpl.java:611)
	at weblogic.jdbc.common.internal.WLDataSourceImpl.getConnection(WLDataSourceImpl.java:604)
	at weblogic.jdbc.common.internal.RmiDataSource.getConnection(RmiDataSource.java:108)
	at oracle.tip.xref.repos.database.SQLUtil.getConnection(SQLUtil.java:138)
	at oracle.tip.xref.repos.database.DatabaseRepositoryMapView.lookupXRef(DatabaseRepositoryMapView.java:439)
	at oracle.tip.xref.XRefManagerImpl.lookupXRef(XRefManagerImpl.java:604)
	at oracle.tip.xref.xpath.XRefXPathFunctions.lookupXRef(XRefXPathFunctions.java:86)
	at oracle.tip.xref.xpath.XRefFunctions$LookupXRef.call(XRefFunctions.java:296)
	at oracle.fabric.common.xml.xpath.FabricXPathFunctionWrapper.evaluate(FabricXPathFunctionWrapper.java:84)
	at oracle.xml.xpath.JXPathContext$JXFunction.invoke(JXPathContext.java:213)
	at oracle.xml.xpath.JXPathContext$JXFunction.invoke(JXPathContext.java:182)
	at oracle.xml.xpath.XPathExtFunction.evaluate(XPathExtFunction.java:337)
	at oracle.xml.xpath.ComparisonExpr.evaluate(XSLExpr.java:1743)
	at oracle.xml.xpath.JXPathExpression.evaluate(JXPathExpression.java:226)
	at oracle.tip.mediator.service.filter.XPathFilterHandler.evaluate(XPathFilterHandler.java:325)
	at oracle.tip.mediator.service.filter.XPathFilterHandler.evaluateFilter(XPathFilterHandler.java:153)
	at oracle.tip.mediator.dispatch.EffectiveCaseType.doFilterEvaluationIfNeeded(EffectiveCaseType.java:59)
	at oracle.tip.mediator.dispatch.MessageDispatcher.executeCase(MessageDispatcher.java:103)
	at oracle.tip.mediator.dispatch.InitialMessageDispatcher.processCase(InitialMessageDispatcher.java:633)
	at oracle.tip.mediator.dispatch.InitialMessageDispatcher.processCases(InitialMessageDispatcher.java:457)
	at oracle.tip.mediator.dispatch.InitialMessageDispatcher.processNormalCases(InitialMessageDispatcher.java:337)
	at oracle.tip.mediator.dispatch.InitialMessageDispatcher.processCases(InitialMessageDispatcher.java:293)
	at oracle.tip.mediator.dispatch.InitialMessageDispatcher.dispatch(InitialMessageDispatcher.java:174)
	at oracle.tip.mediator.serviceEngine.MediatorServiceEngine.process(MediatorServiceEngine.java:1443)
	at oracle.tip.mediator.serviceEngine.MediatorServiceEngine.post(MediatorServiceEngine.java:1171)
	at oracle.integration.platform.blocks.mesh.AsynchronousMessageHandler.doPost(AsynchronousMessageHandler.java:144)
	at oracle.integration.platform.blocks.mesh.MessageRouter.post(MessageRouter.java:254)
	at oracle.integration.platform.blocks.mesh.MeshImpl.post(MeshImpl.java:411)
	at sun.reflect.GeneratedMethodAccessor1777.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
```
Regards,
Piotr

**Comment by tomvit** [comment]
I think this is caused by the fact that I do not format time explicitly but use str representation of it. In https://github.com/ailog-analytics/wls-analytics/commit/810e8a6f240da7c3c22e8119fc40474f572eb993 I added this format function so hopefully this will fix the issue.
